var EsiListeningPost=EsiListeningPost||{};
if(!EsiListeningPost.initialized)EsiListeningPost.version="0.0.1",EsiListeningPost.secure=[],function(j,k){function q(b,c,d,f,a,g){c=escape(c);b=b+"="+c+(d?"; expires="+d.toGMTString():"")+(f?"; path="+f:"")+(a?"; domain="+a:"")+(g?"; secure":"");k.cookie=b}function t(b){var c=b+"=";if(0<k.cookie.length&&(b=k.cookie.indexOf(c),-1!=b)){b+=c.length;c=k.cookie.indexOf(";",b);if(-1==c)c=k.cookie.length;return unescape(k.cookie.substring(b,c))}}function u(){if("undefined"!=typeof j.crypto&&"undefined"!=
typeof j.crypto.getRandomValues){var b=new Uint16Array(8);j.crypto.getRandomValues(b);var c=function(c){for(c=c.toString(16);4>c.length;)c="0"+c;return c};return c(b[0])+c(b[1])+"-"+c(b[2])+"-"+c(b[3])+"-"+c(b[4])+"-"+c(b[5])+c(b[6])+c(b[7])}return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var b=16*Math.random()|0;return("x"==c?b:b&3|8).toString(16)})}function p(b,c){var d=k.createElement("script");d.setAttribute("type","text/javascript");d.setAttribute("src",b);d.readyState?
d.onreadystatechange=function(){("complete"==this.readyState||"loaded"==this.readyState)&&c()}:d.onload=c;(k.getElementsByTagName("head")[0]||k.documentElement).appendChild(d)}function v(b,c,d){c||(c=250);var f;return function(){var a=d||this,g=+new Date;if(!f||g>f+c)f=g,b.apply(a,arguments)}}function w(b){EsiListeningPost.api=new EsiListeningPost.api(b);b.client&&p(EsiListeningPost.REMOTE+"/js/lpost-"+b.client.toLowerCase()+".js",function(){})}function B(){EsiListeningPost.easyXDM=j.easyXDM.noConflict("EsiListeningPost");
x()}function C(){EsiListeningPost.jQuery=j.jQuery.noConflict(!0);y()}function y(){(function d(b,a,g){function l(o,h){if(!a[o]){if(!b[o]){var m="function"==typeof require&&require;if(!h&&m)return m(o,!0);if(e)return e(o,!0);throw Error("Cannot find module "+o+"");}m=a[o]={exports:{}};b[o][0].call(m.exports,function(a){var g=b[o][1][a];return l(g?g:a)},m,m.exports,d,b,a,g)}return a[o].exports}for(var e="function"==typeof require&&require,n=0;n<g.length;n++)l(g[n]);return l})({1:[function(b,f){b=f.exports=
function(a){this._helper=a;this._object={};this._pushes={};this._patterns={validate:/^[a-z][a-z0-9_]*(?:\[(?:\d*|[a-z0-9_]+)\])*$/i,key:/[a-z0-9_]+|(?=\[\])/gi,push:/^$/,fixed:/^\d+$/,named:/^[a-z0-9_]+$/i}};b.prototype._build=function(a,g,b){a[g]=b;return a};b.prototype._makeObject=function(a,g){for(var b=a.match(this._patterns.key),e;void 0!==(e=b.pop());)this._patterns.push.test(e)?(e=this._incrementPush(a.replace(/\[\]$/,"")),g=this._build([],e,g)):this._patterns.fixed.test(e)?g=this._build([],
e,g):this._patterns.named.test(e)&&(g=this._build({},e,g));return g};b.prototype._incrementPush=function(a){void 0===this._pushes[a]&&(this._pushes[a]=0);return this._pushes[a]++};b.prototype.addPair=function(a){if(!this._patterns.validate.test(a.name))return this;a=this._makeObject(a.name,a.value);this._object=this._helper.extend(!0,this._object,a);return this};b.prototype.addPairs=function(a){if(!this._helper.isArray(a))throw Error("formSerializer.addPairs expects an Array");for(var g=0,b=a.length;g<
b;g++)this.addPair(a[g]);return this};b.prototype.serialize=function(){return this._object};b.prototype.serializeJSON=function(){return JSON.stringify(this.serialize())}},{}],2:[function(b,f){f.exports=function(a){if("function"===typeof a.extend)this.extend=a.extend;else throw Error("jQuery is required to use jquery-serialize-object");this.isArray="function"===typeof Array.isArray?Array.isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)}}},{}],3:[function(b){var f=b("./form-serializer"),
a=b("./helper");(function(b){var d=new a(b||{});b.fn.serializeObject=function(){var a=b(this);return 1<a.length?Error("jquery-serialize-object can only serialize one form at a time"):(new f(d)).addPairs(a.serializeArray()).serialize()}})(EsiListeningPost.jQuery)},{"./form-serializer":1,"./helper":2}]},{},[3]);var b=function(b,f){var a=a||{running:!1},g=setInterval(function(){b(l)},f),l=function(){clearInterval(g);a.running=!1};return a};EsiListeningPost.jQuery(k).ready(function(d){var f=b(function(a){if(!(f.running||
"function"==typeof EsiListeningPost.api))EsiListeningPost.api.event({entity:"PAGE",action:"LOAD",params:[{name:"URL",value:k.URL}],success:function(){a()},error:function(){a()}}),f.running=!0},100);EsiListeningPost.secure.push(["type","password"]);EsiListeningPost.secure.push(["name","Card_CCNUMBERNEW"]);EsiListeningPost.secure.push(["id","cvv2code"]);d(document).on("click","a",function(a){var a=d(a.currentTarget),b=a.attr("href"),a=[{name:"id",value:a.attr("id")},{name:"name",value:a.attr("name")},
{name:"value",value:a.text()},{name:"url",value:b},{name:"target",value:a.attr("target")},{name:"title",value:a.attr("title")},{name:"onclick",value:a.attr("onclick")},{name:"class",value:a.attr("class")},{name:"page",value:k.URL}];EsiListeningPost.api.event({entity:"LINK",action:"CLICK",params:a,success:function(){}})});d('[name="loginForm"]').on("submit",v(function(){var a=d(this),b=a.attr("action"),l=a.serializeObject();if(0<EsiListeningPost.secure.length)for(i=0;i<EsiListeningPost.secure.length;i++)EsiListeningPost.secure[i][0]&&
EsiListeningPost.secure[i][1]&&a.find("["+EsiListeningPost.secure[i][0]+'="'+EsiListeningPost.secure[i][1]+'"]').each(function(){var a=d(this).attr("name");a&&(l[a]="********")});a=[{name:"id",value:a.attr("id")},{name:"name",value:a.attr("name")},{name:"action",value:b},{name:"data",value:JSON.stringify(l)},{name:"onclick",value:a.attr("onclick")},{name:"class",value:a.attr("class")}];EsiListeningPost.api.event({entity:"LOGIN",action:"attempt",params:a,success:function(){}})},1E3));d("form").on("submit",
v(function(){var a=d(this),b=a.attr("action"),l=a.serializeObject();if(0<EsiListeningPost.secure.length)for(i=0;i<EsiListeningPost.secure.length;i++)EsiListeningPost.secure[i][0]&&EsiListeningPost.secure[i][1]&&a.find("["+EsiListeningPost.secure[i][0]+'="'+EsiListeningPost.secure[i][1]+'"]').each(function(){var a=d(this).attr("name");a&&(l[a]="********")});a=[{name:"id",value:a.attr("id")},{name:"name",value:a.attr("name")},{name:"action",value:b},{name:"data",value:JSON.stringify(l)},{name:"onclick",
value:a.attr("onclick")},{name:"class",value:a.attr("class")}];EsiListeningPost.api.event({entity:"FORM",action:"SUBMIT",params:a,success:function(){}})},1E3))})}function x(){void 0===j.JSON?p(EsiListeningPost.REMOTE+"/js/json2.js",z):z()}function z(){EsiListeningPost.xhr=new EsiListeningPost.easyXDM.Rpc({swf:EsiListeningPost.REMOTE+"/swf/easyxdm.swf",remote:EsiListeningPost.REMOTE+"/cors/",remoteHelper:EsiListeningPost.REMOTE+"/name.html",lazy:!0},{remote:{request:{}}});j.EsiListeningPostAsyncInit&&
!j.EsiListeningPostAsyncInit.hasRun?(j.EsiListeningPostAsyncInit.hasRun=!0,EsiListeningPostAsyncInit()):EsiListeningPost.initialize({})}EsiListeningPost.REMOTE="https:"==k.location.protocol?"https://lpost.exchangesolutions.com":"http://lpost.exchangesolutions.com";var A=!1,r={},s=new Date((new Date).getTime()+31536E6);EsiListeningPost.initialize=function(b){r=b;EsiListeningPost.initialized?w(r):A=!0};void 0===j.easyXDM||"2.4.17.1"!==j.easyXDM.version?p(EsiListeningPost.REMOTE+"/js/easyXDM.min.js",
B):(EsiListeningPost.easyXDM=j.easyXDM,x());(function(){var b=void 0===j.jQuery;b||(b=j.jQuery.fn.jquery.split("."),b=!(1<b[0]||1==b[0]&&7<=b[1]));return!b})()?(EsiListeningPost.jQuery=j.jQuery,y()):p(EsiListeningPost.REMOTE+"/js/jquery-1.8.0.min.js",C);EsiListeningPost.queue=function(){var b=this,c=[],d=[],f=function(){var a=c.concat(d);-1===EsiListeningPost.store("queuedEvents",a)&&EsiListeningPost.api.trackSingleEvent({entity:"STORAGE",action:"OVERFLOW",params:[{name:"URL",value:k.URL}]})};d.removeByElementKey=
function(a,b){for(i=0;i<this.length;i++)this[i][a]==b&&this.splice(i,1);return this};b.clearEvents=function(){c.length=0};b.addEvent=function(a){c.push(a);f()};b.getEvents=function(){if(!c.length)return!1;var a=c.slice(0);b.clearEvents();var g=u();d.push({id:g,data:a});return{data:a,success:function(){d.removeByElementKey("id",g);f()},error:function(){$.merge(c,a);d.removeByElementKey("id",g);f()}}};(function(){var a=EsiListeningPost.store("queuedEvents");a&&(c=a)})()};EsiListeningPost.api=function(b){var c=
new EsiListeningPost.queue(b),d,f=function(a){var b={"Content-Type":"application/json; charset=utf-8","X-Auth-Key":"3df9bd8e35e7ba8e20eab54c060fd3efc4ea9a1d"};a&&(b["X-Auth-User"]=a);return b},a=function(){var a=t("EsiListeningPost");if(a)return a;a=u();q("EsiListeningPost",a,s,"/");return a},g=function(){var a=t("EsiListeningPost_SeqNum");if(a)return a=parseInt(a)+1,q("EsiListeningPost_SeqNum",a,s,"/"),a;a=0;q("EsiListeningPost_SeqNum",a,s,"/");return a},l=function(a){var b=[];if(a){if("Array"===
Object.prototype.toString.call(a).slice(8,-1))return e(a);if("Object"===Object.prototype.toString.call(a).slice(8,-1))for(var c in a)null!=a[c]&&b.push({name:c,value:a[c].toString()})}return e(b)},e=function(a){a.push({name:"browser info",value:navigator.userAgent});a.push({name:"jquery version",value:EsiListeningPost.jQuery.fn.jquery});a.push({name:"loggedIn",value:"NA"});return a},n=function(){var g=c.getEvents();g&&EsiListeningPost.xhr.request({url:EsiListeningPost.REMOTE+"/api/client/events",
method:"POST",headers:f(a(),b),data:g.data},function(){g.success()},function(){g.success()})};EsiListeningPost.trackEvent=function(b){if(!b)return{error:"Missing Parameters"};if(!b.entity)return{error:"Missing entity"};if(!b.action)return{error:"Missing action"};var e=a(),d=(new Date).getTime(),n=l(b.data);n.push({name:"clientInitiated",value:!0});b={when:d,user:e,entity:b.entity||"",action:b.action||"",additionalData:n||{},seqNum:g()};c.addEvent(b);return{success:!0}};return{event:function(e){var h=
a(),f=b.success,j=(new Date).getTime(),e=e||{},k=l(e.params);if(e.user)h=e.user;if(e.success)f=e.success;h={when:j,user:h,entity:e.entity||"",action:e.action||"",additionalData:k,seqNum:g()};c.addEvent(h);if(!d){n();h=1E4;if(EsiListeningPost.delayConfig&&EsiListeningPost.delayConfig.pushData)h=EsiListeningPost.delayConfig.pushData;d=setInterval(n,h)}f()},trackSingleEvent:function(c){var e=a(),d=(new Date).getTime(),c=c||{},n=l(c.params),e=[{when:d,user:e,entity:c.entity||"",action:c.action||"",additionalData:n,
seqNum:g()}];EsiListeningPost.xhr.request({url:EsiListeningPost.REMOTE+"/api/client/events",method:"POST",headers:f(a(),b),data:e},function(){},function(){})}}};A&&w(r);(function(){function b(a,b){c.addType(a,function(e,d,f){var h,m=d,j=(new Date).getTime();if(!e){m={};f=[];d=0;try{for(e=b.length;e=b.key(d++);)if(rprefix.test(e))h=JSON.parse(b.getItem(e)),h.expires&&h.expires<=j?f.push(e):m[e.replace(rprefix,"")]=h.data;for(;e=f.pop();)b.removeItem(e)}catch(k){}return m}e="__esi__"+e;if(void 0===
d)if(h=(h=b.getItem(e))?JSON.parse(h):{expires:-1},h.expires&&h.expires<=j)b.removeItem(e);else return h.data;else if(null===d)b.removeItem(e);else{h=JSON.stringify({data:d,expires:f.expires?j+f.expires:null});try{b.setItem(e,h)}catch(p){c[a]();try{b.setItem(e,h)}catch(q){return-1;throw c.error();}}}return m})}var c=EsiListeningPost.store=function(a,b,e){var d=c.type;if(e&&e.type&&e.type in c.types)d=e.type;return c.types[d](a,b,e||{})};c.types={};c.type=null;c.addType=function(a,b){if(!c.type)c.type=
a;c.types[a]=b;c[a]=function(b,d,f){f=f||{};f.type=a;return c(b,d,f)}};c.error=function(){return"esi.store quota exceeded"};for(var d in{localStorage:1,sessionStorage:1})try{window[d].setItem("__esi__","x"),window[d].removeItem("__esi__"),b(d,window[d])}catch(f){}if(!c.types.localStorage&&window.globalStorage)try{if(b("globalStorage",window.globalStorage[window.location.hostname]),"sessionStorage"===c.type)c.type="globalStorage"}catch(a){}(function(){if(!c.types.localStorage){var a=document.createElement("div");
a.style.display="none";document.getElementsByTagName("head")[0].appendChild(a);try{a.addBehavior("#default#userdata"),a.load("esi")}catch(b){a.parentNode.removeChild(a);return}c.addType("userData",function(b,d,f){a.load("esi");var h,j,k=d,l=(new Date).getTime();if(!b){k={};j=[];for(b=0;d=a.XMLDocument.documentElement.attributes[b++];)h=JSON.parse(d.value),h.expires&&h.expires<=l?j.push(d.name):k[d.name]=h.data;for(;b=j.pop();)a.removeAttribute(b);a.save("esi");return k}b=b.replace(/[^\-._0-9A-Za-z\xb7\xc0-\xd6\xd8-\xf6\xf8-\u037d\u037f-\u1fff\u200c-\u200d\u203f\u2040\u2070-\u218f]/g,
"-");b=b.replace(/^-/,"_-");if(void 0===d)if(h=(d=a.getAttribute(b))?JSON.parse(d):{expires:-1},h.expires&&h.expires<=l)a.removeAttribute(b);else return h.data;else null===d?a.removeAttribute(b):(j=a.getAttribute(b),h=JSON.stringify({data:d,expires:f.expires?l+f.expires:null}),a.setAttribute(b,h));try{a.save("esi")}catch(p){null===j?a.removeAttribute(b):a.setAttribute(b,j);c.userData();try{a.setAttribute(b,h),a.save("esi")}catch(q){null===j?a.removeAttribute(b):a.setAttribute(b,j);return-1;throw c.error();
}}return k})}})()})();EsiListeningPost.initialized=!0}(window,document);